# Generated by Django 5.1.1 on 2024-09-29 18:00

import django.db.models.deletion
import shop_app.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=500)),
                ("image", models.ImageField(upload_to=shop_app.models.getFileName)),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("vender", models.CharField(max_length=50)),
                ("quantity", models.IntegerField()),
                ("old_price", models.FloatField()),
                ("new_price", models.FloatField()),
                ("description", models.TextField(max_length=500)),
                ("seller", models.FloatField()),
                (
                    "product_image",
                    models.ImageField(upload_to=shop_app.models.getFileName),
                ),
                (
                    "status",
                    models.BooleanField(default=False, help_text="0-show,1-Hidden"),
                ),
                (
                    "trending",
                    models.BooleanField(default=False, help_text="0-default,1-Hidden"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop_app.category",
                    ),
                ),
            ],
        ),
    ]
